# # Example

# install portainer
- name: Create a volume
  community.docker.docker_volume:
    name: portainer_data

- name: Install portainer
  community.docker.docker_container:
    name: portainer
    image: portainer/portainer-ce
    restart_policy: always
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"

# # install rabbitmq
# - name: Install rabbitmq
#   community.docker.docker_container:
#     name: rabbitmq
#     image: rabbitmq:3.9-management
#     restart_policy: always
#     ports:
#       - "5672:5672"
#       - "15672:15672"
#     env:
#       RABBITMQ_DEFAULT_USER: "admin"
#       RABBITMQ_DEFAULT_PASS: "password"
