- name: Download the Docker CE signing key
  ansible.builtin.get_url:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    dest: "/etc/apt/keyrings/docker.asc"
    mode: "0644"

- name: Add Docker APT repository
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ docker_arch }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
    update_cache: true

# install docker
- name: Install docker
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - docker-buildx-plugin
      - docker-compose-plugin
      - docker-ce-rootless-extras
      - containerd.io
      - python3-docker
    update_cache: true
    state: latest
  notify: Restart docker

- name: Check service
  ansible.builtin.systemd:
    daemon_reload: true
    name: docker.service
    enabled: true
    state: started
    masked: false
