# install portainer
- name: Create a volume
  community.docker.docker_volume:
    name: portainer_volume

- name: Create a network
  community.docker.docker_network:
    name: portainer_network
    ipam_config:
      - subnet: "{{ docker_portainer_network }}"
        gateway: "{{ docker_portainer_gateway }}"

- name: Install portainer
  community.docker.docker_container:
    name: portainer
    image: portainer/portainer-ce
    restart_policy: always
    networks:
      - name: portainer_network
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_volume:/data"
